### ISSUE TITLE
No network when accessing Membership after uninstalling omnipay extension

### ISSUE THREAD

**Issue by shaesen** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#44] opened 2018-02-13 21:17 UTC
Hi Eileen, 
I've got a weird issue with omnipay extension. I uninstalled and removed it and after doing so several buttons on the contact page return a network error (f.i. Membership). Reinstalling Omnipay extension solves the issue. Any idea what could be wrong ? And also after reinstalling I get an error on the activation of (any) other extension. "API error: DB Error: already exists" which seems related to Omnipay extension.

Thanks for looking into this,
Stefaan

**Comment by eileenmcnaughton** [comment] 2018-02-13 21:30
hmm - the problem is it's looking for a class no longer enabled. The 4.7.31 rc has a patch that might fix it - it should have been cut last week for trials but I think is still pending

**Comment by shaesen** [comment] 2018-02-13 21:37
Thanks Eileen, I'll give it a try and will let you know. The second issue has just got clearer (I enabled an error reporting extension :p) and it seems I did not remove ALL payment_processor_type records related to omnipay (Mollie, probably because I use it). Will give it another try too ! Q: Wouldn't it be possible to check presence rather than adding anyway ?

**Comment by eileenmcnaughton** [comment] 2018-02-13 21:47
right - there is a patch merged into master that checks for a class

**Comment by mattwire** [comment] 2018-09-13 22:02
Hey this can be closed as the patch was merged into 4.7.31

**Comment by eileenmcnaughton** [comment] 2018-09-13 22:03
done

**Closed by eileenmcnaughton** 2018-09-13 22:03 UTC
