### ISSUE TITLE
Fatal error Call to undefined method CRM_Core_payment_omnipayMultiProcessor::doTransferCheckout(0 in /sites/all/modules/webform_civicrm/includes/wf_crm_webform_postprocess.inc on line 1841

### ISSUE THREAD

**Issue by jvos** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#35] opened 2017-09-19 09:34 UTC
We are using the Drupal modules webform and webform_civicrm with this extension. 
Versions older then 2.2 work fine, but in newer releases we get the following error message when we submit the Drupal webform to the mollie payment 
"Fatal error Call to undefined method CRM_Core_payment_omnipayMultiProcessor::doTransferCheckout(0 in /sites/all/modules/webform_civicrm/includes/wf_crm_webform_postprocess.inc on line 1841".

**Comment by eileenmcnaughton** [comment] 2017-09-20 05:00
arg - I removed that function as part of removing support for 4.6 but it didn't occur to me webform might use it. What version of civi/ webform are you using?

**Comment by eileenmcnaughton** [comment] 2017-09-23 06:53
Can you try this patch (against webform_civicrm)

https://github.com/colemanw/webform_civicrm/pull/86

**Comment by jvos** [comment] 2017-09-25 08:10
Thanks for the patch, i will try it. Beside, the version of civicrm is 4.7.18 or higher and the version of the webform_civicrm module is 7.x-4.18

**Comment by eileenmcnaughton** [comment] 2017-09-25 20:22
I realised you need this change too 
https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/commit/a915787ca9b930b89722fa7163898437f1d9ebba

**Comment by jvos** [comment] 2017-09-26 06:42
Thanks again ! I have lookes at the file but the last changes (from  a915787) are already in release 2.4 !

**Comment by jaapjansma** [comment] 2017-10-09 11:08
The problem @jvos is addressing is not fixed yet. It has something to do with the webform and civicrm core payment processor handling. When I setup a payment processor for paypal I get the same error. 

The webform module tries to call a function doTransferCheckout but that one does not exist.

**Comment by eileenmcnaughton** [comment] 2017-10-09 11:22
That's probably because a new release of webform_civicrm has not yet been tagged

**Comment by jaapjansma** [comment] 2017-10-09 11:24
@eileenmcnaughton you mean a new release of webform_civicrm is underway which contains a fix for this?

Mean while I also found this issue on the webform_civicrm module: https://www.drupal.org/node/2558585
That issue is open since 2015

**Comment by jaapjansma** [comment] 2017-10-09 11:25
@eileenmcnaughton I see that there is indeed a new version of webform_civicrm which seems to contain a fix

**Comment by jaapjansma** [comment] 2017-10-09 11:31
@eileenmcnaughton @jvos I can confirm that this is fixed in webform_civicrm 7.x-4.19

**Comment by eileenmcnaughton** [comment] 2017-10-10 03:25
Thanks @jaapjansma

**Closed** 2017-10-10 03:25 UTC
